// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq04VBJ1-EZ5NQyEODtOiTTFKuaLyXtZU',
    appId: '1:489078508896:android:5cb1eb4e0bbe982495a205',
    messagingSenderId: '489078508896',
    projectId: 'spacex-firebase-as',
    storageBucket: 'spacex-firebase-as.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzstI-x2fbOiMV05Ot6AwSSQCN60XyNYA',
    appId: '1:489078508896:ios:8077900a1afb08a795a205',
    messagingSenderId: '489078508896',
    projectId: 'spacex-firebase-as',
    storageBucket: 'spacex-firebase-as.firebasestorage.app',
    iosBundleId: 'com.example.spacexFirebaseAs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzstI-x2fbOiMV05Ot6AwSSQCN60XyNYA',
    appId: '1:489078508896:ios:8077900a1afb08a795a205',
    messagingSenderId: '489078508896',
    projectId: 'spacex-firebase-as',
    storageBucket: 'spacex-firebase-as.firebasestorage.app',
    iosBundleId: 'com.example.spacexFirebaseAs',
  );
}
